FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    && apt-get install -y build-essential \
    && apt-get install -y libpq-dev gcc \
    && rm -rf /var/lib/apt/lists/* \
    && pip install psycopg2

WORKDIR /usr/src/message-manager-api

ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip
COPY ./requirements.txt /usr/src/message-manager-api/requirements.txt
RUN pip install -r requirements.txt virtualenv

COPY . .

EXPOSE 5001

CMD ["./run.sh"]
